// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Creator struct {
	Name  string     `json:"name"`
	Works []*Crystal `json:"Works"`
}

type Crystal struct {
	ID      int    `json:"id"`
	Title   string `json:"title"`
	Creator string `json:"Creator"`
	Owner   string `json:"Owner"`
}

type Owner struct {
	Name string     `json:"name"`
	Owns []*Crystal `json:"Owns"`
}
